/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DisplayIndexRouteImport } from './routes/display/index'
import { Route as AdminManageRouteImport } from './routes/admin/manage'
import { Route as AdminAuctionRouteImport } from './routes/admin/auction'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplayIndexRoute = DisplayIndexRouteImport.update({
  id: '/display/',
  path: '/display/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminManageRoute = AdminManageRouteImport.update({
  id: '/admin/manage',
  path: '/admin/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuctionRoute = AdminAuctionRouteImport.update({
  id: '/admin/auction',
  path: '/admin/auction',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/auction': typeof AdminAuctionRoute
  '/admin/manage': typeof AdminManageRoute
  '/display': typeof DisplayIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/auction': typeof AdminAuctionRoute
  '/admin/manage': typeof AdminManageRoute
  '/display': typeof DisplayIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/auction': typeof AdminAuctionRoute
  '/admin/manage': typeof AdminManageRoute
  '/display/': typeof DisplayIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin/auction' | '/admin/manage' | '/display'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin/auction' | '/admin/manage' | '/display'
  id: '__root__' | '/' | '/admin/auction' | '/admin/manage' | '/display/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAuctionRoute: typeof AdminAuctionRoute
  AdminManageRoute: typeof AdminManageRoute
  DisplayIndexRoute: typeof DisplayIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/display/': {
      id: '/display/'
      path: '/display'
      fullPath: '/display'
      preLoaderRoute: typeof DisplayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/manage': {
      id: '/admin/manage'
      path: '/admin/manage'
      fullPath: '/admin/manage'
      preLoaderRoute: typeof AdminManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/auction': {
      id: '/admin/auction'
      path: '/admin/auction'
      fullPath: '/admin/auction'
      preLoaderRoute: typeof AdminAuctionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAuctionRoute: AdminAuctionRoute,
  AdminManageRoute: AdminManageRoute,
  DisplayIndexRoute: DisplayIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
